<?php 

class Front_Page {

    public static function init() {
        add_action( 'acf/init', [__CLASS__, 'acf_add_local_field_group'] );

        add_action('wp_ajax_nopriv_front_page_search', [__CLASS__, 'front_page_search']);
        add_action('wp_ajax_front_page_search', [__CLASS__, 'front_page_search']);
    }

    public static function front_page_search() {
        $type = $_POST['type'];
        $appointment = $_POST['appointment'];
        $type = get_term( $type, 'type' );

        $redirect_url = get_category_link($type->term_id).'?taxonomy=type&slug=' .$type->slug . '&appointment_array=' . $appointment;

        wp_send_json_success( ['redirect_url' => $redirect_url], 200 );
    }

    public static function acf_add_local_field_group() {

        if ( function_exists('acf_add_local_field_group') ):

            acf_add_local_field_group(array(
                'key' => 'group_64921bac76be4',
                'title' => 'Front page',
                'fields' => array(
                    array(
                        'key' => 'field_64921bdffba71',
                        'label' => 'Promo section',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_64921fbbfba72',
                        'label' => '',
                        'name' => 'promo_section',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_64921ff9fba73',
                                'label' => 'Slider',
                                'name' => 'slider',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'pagination' => 0,
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Add Row',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_64922007fba74',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'translations' => 'translate',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'placeholder' => '',
                                        'new_lines' => 'br',
                                        'parent_repeater' => 'field_64921ff9fba73',
                                    ),
                                    array(
                                        'key' => 'field_64922014fba75',
                                        'label' => 'Text',
                                        'name' => 'text',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'translations' => 'translate',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'placeholder' => '',
                                        'new_lines' => 'br',
                                        'parent_repeater' => 'field_64921ff9fba73',
                                    ),
                                    array(
                                        'key' => 'field_6492201efba76',
                                        'label' => 'Image',
                                        'name' => 'image',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'library' => 'all',
                                        'translations' => 'copy_once',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'medium',
                                        'parent_repeater' => 'field_64921ff9fba73',
                                    ),
                                    array(
                                        'key' => 'field_6492202efba77',
                                        'label' => 'Video',
                                        'name' => 'video',
                                        'aria-label' => '',
                                        'type' => 'file',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'library' => 'all',
                                        'translations' => 'copy_once',
                                        'min_size' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'parent_repeater' => 'field_64921ff9fba73',
                                    ),
                                    array(
                                        'key' => 'field_64922056fba78',
                                        'label' => 'Button',
                                        'name' => 'button',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'translations' => 'copy_once',
                                        'parent_repeater' => 'field_64921ff9fba73',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6499ca5506689',
                        'label' => 'Banner section',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_6499ca650668a',
                        'label' => '',
                        'name' => 'banner_section',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6499ca960668b',
                                'label' => 'Title',
                                'name' => 'title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_6499caa30668c',
                                'label' => 'Subtitle',
                                'name' => 'subtitle',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'rows' => 2,
                                'placeholder' => '',
                                'new_lines' => 'br',
                            ),
                            array(
                                'key' => 'field_6499caa90668d',
                                'label' => 'Background image',
                                'name' => 'background_image',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'library' => 'all',
                                'translations' => 'copy_once',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                            array(
                                'key' => 'field_6499cae20668e',
                                'label' => 'Image cutout',
                                'name' => 'image_cutout',
                                'aria-label' => '',
                                'type' => 'image',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'url',
                                'library' => 'all',
                                'translations' => 'copy_once',
                                'min_width' => '',
                                'min_height' => '',
                                'min_size' => '',
                                'max_width' => '',
                                'max_height' => '',
                                'max_size' => '',
                                'mime_types' => '',
                                'preview_size' => 'medium',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6499cddd2d104',
                        'label' => 'Main banner section',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_6499cdfd2d105',
                        'label' => '',
                        'name' => 'main_banner_section',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6499cf242d106',
                                'label' => 'Info cards',
                                'name' => 'info_cards',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'pagination' => 0,
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Add Row',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_6499cf862d107',
                                        'label' => 'Background image',
                                        'name' => 'background_image',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'library' => 'all',
                                        'translations' => 'copy_once',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'medium',
                                        'parent_repeater' => 'field_6499cf242d106',
                                    ),
                                    array(
                                        'key' => 'field_6499cf972d108',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'translations' => 'translate',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'parent_repeater' => 'field_6499cf242d106',
                                    ),
                                    array(
                                        'key' => 'field_6499cfa22d109',
                                        'label' => 'Text',
                                        'name' => 'text',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'translations' => 'translate',
                                        'maxlength' => '',
                                        'rows' => 3,
                                        'placeholder' => '',
                                        'new_lines' => 'br',
                                        'parent_repeater' => 'field_6499cf242d106',
                                    ),
                                    array(
                                        'key' => 'field_6499cfb42d10a',
                                        'label' => 'Button',
                                        'name' => 'button',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'translations' => 'copy_once',
                                        'parent_repeater' => 'field_6499cf242d106',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6499d4b10be58',
                        'label' => 'Benefits section',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_65325c3735c6d',
                        'label' => '',
                        'name' => 'benefits_section',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_65325c5235c6e',
                                'label' => 'Title',
                                'name' => 'title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_65325c5a35c6f',
                                'label' => 'Text',
                                'name' => 'text',
                                'aria-label' => '',
                                'type' => 'textarea',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'rows' => '',
                                'placeholder' => '',
                                'new_lines' => 'br',
                            ),
                            array(
                                'key' => 'field_65325c6035c70',
                                'label' => 'Button',
                                'name' => 'button',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'translations' => 'copy_once',
                            ),
                            array(
                                'key' => 'field_65325c7435c71',
                                'label' => 'Benefits',
                                'name' => 'benefits',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'table',
                                'pagination' => 0,
                                'min' => 0,
                                'max' => 0,
                                'collapsed' => '',
                                'button_label' => 'Add Row',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_65325c9a35c72',
                                        'label' => 'Image',
                                        'name' => 'image',
                                        'aria-label' => '',
                                        'type' => 'image',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'url',
                                        'library' => 'all',
                                        'translations' => 'copy_once',
                                        'min_width' => '',
                                        'min_height' => '',
                                        'min_size' => '',
                                        'max_width' => '',
                                        'max_height' => '',
                                        'max_size' => '',
                                        'mime_types' => '',
                                        'preview_size' => 'medium',
                                        'parent_repeater' => 'field_65325c7435c71',
                                    ),
                                    array(
                                        'key' => 'field_65325ca835c73',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'translations' => 'translate',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                        'parent_repeater' => 'field_65325c7435c71',
                                    ),
                                    array(
                                        'key' => 'field_65325cae35c74',
                                        'label' => 'Text',
                                        'name' => 'text',
                                        'aria-label' => '',
                                        'type' => 'textarea',
                                        'instructions' => '',
                                        'required' => 0,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'translations' => 'translate',
                                        'maxlength' => '',
                                        'rows' => '',
                                        'placeholder' => '',
                                        'new_lines' => 'br',
                                        'parent_repeater' => 'field_65325c7435c71',
                                    ),
                                ),
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_64b51c4adb15e',
                        'label' => 'Categories section',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_64b51c7adb160',
                        'label' => '',
                        'name' => 'сategories_section',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_64b51ca2db161',
                                'label' => 'First category',
                                'name' => 'first_category',
                                'aria-label' => '',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'appointment',
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'translations' => 'copy_once',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_64b51cefdb162',
                                'label' => 'Second category',
                                'name' => 'second_category',
                                'aria-label' => '',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'appointment',
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'translations' => 'copy_once',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_64b51cf2db163',
                                'label' => 'Third category',
                                'name' => 'third_category',
                                'aria-label' => '',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'appointment',
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'translations' => 'copy_once',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_64b51cf4db164',
                                'label' => 'Fourth category',
                                'name' => 'fourth_category',
                                'aria-label' => '',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'appointment',
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'translations' => 'copy_once',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_64b51cf6db165',
                                'label' => 'Fifth category',
                                'name' => 'fifth_category',
                                'aria-label' => '',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'appointment',
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'translations' => 'copy_once',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_64b51cf8db166',
                                'label' => 'Sixth category',
                                'name' => 'sixth_category',
                                'aria-label' => '',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'appointment',
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'translations' => 'copy_once',
                                'multiple' => 0,
                            ),
                            array(
                                'key' => 'field_64b51cfadb167',
                                'label' => 'Seventh category',
                                'name' => 'seventh_category',
                                'aria-label' => '',
                                'type' => 'taxonomy',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'taxonomy' => 'appointment',
                                'add_term' => 0,
                                'save_terms' => 0,
                                'load_terms' => 0,
                                'return_format' => 'object',
                                'field_type' => 'select',
                                'allow_null' => 0,
                                'translations' => 'copy_once',
                                'multiple' => 0,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_64bb9eb59edfa',
                        'label' => 'Product section',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_64bb9ec29edfb',
                        'label' => '',
                        'name' => 'product_section',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_64bb9ee59edfc',
                                'label' => 'Title',
                                'name' => 'title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_64bb9eeb9edfd',
                                'label' => 'Text',
                                'name' => 'text',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_64bb9ef09edfe',
                                'label' => 'Products',
                                'name' => 'products',
                                'aria-label' => '',
                                'type' => 'relationship',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'post_type' => array(
                                    0 => 'product',
                                ),
                                'post_status' => '',
                                'taxonomy' => '',
                                'filters' => array(
                                    0 => 'search',
                                ),
                                'return_format' => 'id',
                                'translations' => 'copy_once',
                                'min' => '',
                                'max' => '7',
                                'elements' => '',
                            ),
                            array(
                                'key' => 'field_6532215c6035c70',
                                'label' => 'Link under selects',
                                'name' => 'link',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'translations' => 'copy_once',
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_6499f3a913ef0',
                        'label' => 'News section',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'top',
                        'endpoint' => 0,
                    ),
                    array(
                        'key' => 'field_6499f3bb13ef1',
                        'label' => '',
                        'name' => 'news_section',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6499f3cc13ef2',
                                'label' => 'Title',
                                'name' => 'title',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                            array(
                                'key' => 'field_6499f3e313ef3',
                                'label' => 'Blog link text',
                                'name' => 'archive_link_text',
                                'aria-label' => '',
                                'type' => 'text',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'default_value' => '',
                                'translations' => 'translate',
                                'maxlength' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                            ),
                        ),
                    ),
//                    array(
//                        'key' => 'field_65363847c64dd',
//                        'label' => 'Month',
//                        'name' => '',
//                        'aria-label' => '',
//                        'type' => 'tab',
//                        'instructions' => '',
//                        'required' => 0,
//                        'conditional_logic' => 0,
//                        'wrapper' => array(
//                            'width' => '',
//                            'class' => '',
//                            'id' => '',
//                        ),
//                        'placement' => 'top',
//                        'endpoint' => 0,
//                    ),
//                    array(
//                        'key' => 'field_65363858c64de',
//                        'label' => '',
//                        'name' => 'month',
//                        'aria-label' => '',
//                        'type' => 'group',
//                        'instructions' => '',
//                        'required' => 0,
//                        'conditional_logic' => 0,
//                        'wrapper' => array(
//                            'width' => '',
//                            'class' => '',
//                            'id' => '',
//                        ),
//                        'layout' => 'block',
//                        'sub_fields' => array(
//                            array(
//                                'key' => 'field_6536386fc64df',
//                                'label' => 'January',
//                                'name' => 'month_1',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_65363876c64e0',
//                                'label' => 'February',
//                                'name' => 'month_2',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_6536387dc64e1',
//                                'label' => 'March',
//                                'name' => 'month_3',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_65363885c64e2',
//                                'label' => 'April',
//                                'name' => 'month_4',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_6536388dc64e3',
//                                'label' => 'May',
//                                'name' => 'month_5',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_65363894c64e4',
//                                'label' => 'June',
//                                'name' => 'month_6',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_6536389bc64e5',
//                                'label' => 'July',
//                                'name' => 'month_7',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_653638a1c64e6',
//                                'label' => 'August',
//                                'name' => 'month_8',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_653638b4c64e7',
//                                'label' => 'September',
//                                'name' => 'month_9',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_653638bbc64e8',
//                                'label' => 'October',
//                                'name' => 'month_10',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_653638c3c64e9',
//                                'label' => 'November',
//                                'name' => 'month_11',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                            array(
//                                'key' => 'field_653638cac64ea',
//                                'label' => 'December',
//                                'name' => 'month_12',
//                                'aria-label' => '',
//                                'type' => 'text',
//                                'instructions' => '',
//                                'required' => 0,
//                                'conditional_logic' => 0,
//                                'wrapper' => array(
//                                    'width' => '',
//                                    'class' => '',
//                                    'id' => '',
//                                ),
//                                'default_value' => '',
//                                'translations' => 'translate',
//                                'maxlength' => '',
//                                'placeholder' => '',
//                                'prepend' => '',
//                                'append' => '',
//                            ),
//                        ),
//                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'page_template',
                            'operator' => '==',
                            'value' => 'front-page.php',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'default',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));            
            
        endif;
               
    }
}